config/routes.rb
Componente2::Application.routes.draw do
  resources :c2s

  resources :clientes

end

app/models/c2.rb
class C2 < ActiveRecord::Base
end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/c2s_controller.rb
class C2sController < ApplicationController
  # GET /c2s
  # GET /c2s.xml
  def index
    @c2s = C2.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @c2s }
    end
  end

  # GET /c2s/1
  # GET /c2s/1.xml
  def show
    @c2 = C2.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @c2 }
    end
  end

  # GET /c2s/new
  # GET /c2s/new.xml
  def new
    @c2 = C2.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @c2 }
    end
  end

  # GET /c2s/1/edit
  def edit
    @c2 = C2.find(params[:id])
  end

  # POST /c2s
  # POST /c2s.xml
  def create
    @c2 = C2.new(params[:c2])

    respond_to do |format|
      if @c2.save
        format.html { redirect_to(@c2, :notice => 'C2 was successfully created.') }
        format.xml  { render :xml => @c2, :status => :created, :location => @c2 }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @c2.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /c2s/1
  # PUT /c2s/1.xml
  def update
    @c2 = C2.find(params[:id])

    respond_to do |format|
      if @c2.update_attributes(params[:c2])
        format.html { redirect_to(@c2, :notice => 'C2 was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @c2.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /c2s/1
  # DELETE /c2s/1.xml
  def destroy
    @c2 = C2.find(params[:id])
    @c2.destroy

    respond_to do |format|
      format.html { redirect_to(c2s_url) }
      format.xml  { head :ok }
    end
  end
end

app/controllers/clientes_controller.rb
class ClientesController < ApplicationController
  # GET /clientes
  # GET /clientes.xml
  def index
    @clientes = Cliente.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @clientes }
    end
  end

  # GET /clientes/1
  # GET /clientes/1.xml
  def show
    id = params[:id]
    cpf_consulta = id[id.length-1..id.length]

    if cpf_consulta == "2"
     saida = {:erro => "-1"}
     respond_to do |format|
       format.js  { render :json => saida}
       format.xml  { render :xml => saida}
     end
     return
    end

    consulta = Cliente.where(:cpf => cpf_consulta)
    if consulta.present?
      @cliente = consulta[0]
    else
      consulta = Cliente.where(:cpf => params[:id])
      if consulta.present?
        @cliente = consulta[0]
      else
        @cliente = Cliente.find(params[:id])
      end
    end

    if @cliente
      @cliente.cpf = id
    end
    respond_to do |format|
      format.html # show.html.erb
      format.js  { render :json => @cliente}
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/new
  # GET /clientes/new.xml
  def new
    @cliente = Cliente.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @cliente }
    end
  end

  # GET /clientes/1/edit
  def edit
    @cliente = Cliente.find(params[:id])
  end

  # POST /clientes
  # POST /clientes.xml
  def create
    @cliente = Cliente.new(params[:cliente])

    respond_to do |format|
      if @cliente.save
        format.html { redirect_to(@cliente, :notice => 'Cliente was successfully created.') }
        format.xml  { render :xml => @cliente, :status => :created, :location => @cliente }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /clientes/1
  # PUT /clientes/1.xml
  def update
    @cliente = Cliente.find(params[:id])

    respond_to do |format|
      if @cliente.update_attributes(params[:cliente])
        format.html { redirect_to(@cliente, :notice => 'Cliente was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @cliente.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /clientes/1
  # DELETE /clientes/1.xml
  def destroy
    @cliente = Cliente.find(params[:id])
    @cliente.destroy

    respond_to do |format|
      format.html { redirect_to(clientes_url) }
      format.xml  { head :ok }
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/c2s_helper.rb
module C2sHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/views/c2s/_form.html.erb
<%= form_for(@c2) do |f| %>
  <% if @c2.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@c2.errors.count, "error") %> prohibited this c2 from being saved:</h2>

      <ul>
      <% @c2.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/c2s/edit.html.erb
<h1>Editing c2</h1>

<%= render 'form' %>

<%= link_to 'Show', @c2 %> |
<%= link_to 'Back', c2s_path %>

app/views/c2s/index.html.erb
<h1>Listing c2s</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @c2s.each do |c2| %>
  <tr>
    <td><%= link_to 'Show', c2 %></td>
    <td><%= link_to 'Edit', edit_c2_path(c2) %></td>
    <td><%= link_to 'Destroy', c2, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New C2', new_c2_path %>

app/views/c2s/new.html.erb
<h1>New c2</h1>

<%= render 'form' %>

<%= link_to 'Back', c2s_path %>

app/views/c2s/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_c2_path(@c2) %> |
<%= link_to 'Back', c2s_path %>

app/views/clientes/_form.html.erb
<%= form_for(@cliente) do |f| %>
  <% if @cliente.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cliente.errors.count, "error") %> prohibited this cliente from being saved:</h2>

      <ul>
      <% @cliente.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cpf %><br />
    <%= f.text_field :cpf %>
  </div>
  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :data_nascimento %><br />
    <%= f.date_select :data_nascimento %>
  </div>
  <div class="field">
    <%= f.label :cep %><br />
    <%= f.text_field :cep %>
  </div>
  <div class="field">
    <%= f.label :complemento %><br />
    <%= f.text_field :complemento %>
  </div>
  <div class="field">
    <%= f.label :ddd %><br />
    <%= f.text_field :ddd %>
  </div>
  <div class="field">
    <%= f.label :telefone %><br />
    <%= f.text_field :telefone %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clientes/edit.html.erb
<h1>Editing cliente</h1>

<%= render 'form' %>

<%= link_to 'Show', @cliente %> |
<%= link_to 'Back', clientes_path %>

app/views/clientes/index.html.erb
<h1>Listing clientes</h1>

<table>
  <tr>
    <th>Cpf</th>
    <th>Nome</th>
    <th>Data nascimento</th>
    <th>Cep</th>
    <th>Complemento</th>
    <th>Ddd</th>
    <th>Telefone</th>
    <th>Email</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clientes.each do |cliente| %>
  <tr>
    <td><%= cliente.cpf %></td>
    <td><%= cliente.nome %></td>
    <td><%= cliente.data_nascimento %></td>
    <td><%= cliente.cep %></td>
    <td><%= cliente.complemento %></td>
    <td><%= cliente.ddd %></td>
    <td><%= cliente.telefone %></td>
    <td><%= cliente.email %></td>
    <td><%= link_to 'Show', cliente %></td>
    <td><%= link_to 'Edit', edit_cliente_path(cliente) %></td>
    <td><%= link_to 'Destroy', cliente, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cliente', new_cliente_path %>

app/views/clientes/new.html.erb
<h1>New cliente</h1>

<%= render 'form' %>

<%= link_to 'Back', clientes_path %>

app/views/clientes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Cpf:</b>
  <%= @cliente.cpf %>
</p>

<p>
  <b>Nome:</b>
  <%= @cliente.nome %>
</p>

<p>
  <b>Data nascimento:</b>
  <%= @cliente.data_nascimento %>
</p>

<p>
  <b>Cep:</b>
  <%= @cliente.cep %>
</p>

<p>
  <b>Complemento:</b>
  <%= @cliente.complemento %>
</p>

<p>
  <b>Ddd:</b>
  <%= @cliente.ddd %>
</p>

<p>
  <b>Telefone:</b>
  <%= @cliente.telefone %>
</p>

<p>
  <b>Email:</b>
  <%= @cliente.email %>
</p>


<%= link_to 'Edit', edit_cliente_path(@cliente) %> |
<%= link_to 'Back', clientes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Componente2</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>